### PR TITLE
add create checklist

### PR DESCRIPTION
**Pull request by azediv**
Create checklist from card id, copy from another function
it need improvment such as getting checklist id
with checklist id, checklist items can be created
first pull request, please be indulgent if it's not the correct way

### CODE REVIEW

**Comment by syntax922** [comment]
Awesome, do you want to have more for the checklist though? Such as adding items and/or marking complete? As is it will only create the checklist. I would also recommend having the return message include the URL to the card.

**Comment by azediv** [comment]
Yes this would be great to have ability to create items in checklist
-  Provide checklist id after creation
- List checklist on a card (with checklist name and id)  if multiple
- Add items to a checklist id (and provide item id as results)
- List items on a checklist id
- Check items on  a checklist id

Have did some tests but not being a dev do not help :)
I'll continue digging !
Thanks for your work, very useful !
Cheers

**Comment by syntax922** [comment]
@azediv have you done more work on this? Were you wanting me to?

**Comment by azediv** [comment]
@syntax922 I did some test but not successful due to lack of skills... :(
if you have time to dig on this I would be happy to test :)

**Pull request closed without merging**
